[versions]
composeDesktop = "1.0.0"
ideaGradlePlugin = "1.3.0"
jna = "5.10.0"
kotlin = "1.5.31"

[libraries]
jna = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinJs = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeDesktop = { id = "org.jetbrains.compose", version.ref = "composeDesktop" }
ideaGradlePlugin = { id = "org.jetbrains.intellij", version.ref = "ideaGradlePlugin" }
